# Generated by Django 5.2 on 2026-09-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='profile_picture_url',
            field=models.TextField(blank=True),
        ),
    ]
