# Generated by Django 5.2 on 2026-09-14 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raffles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('SINGLE', 'Avulso — 1 sorteio (R$10)'), ('PACK_30', 'Pacote — 30 sorteios (R$100)')], max_length=20)),
                ('credits', models.IntegerField()),
                ('price_cents', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando pagamento'), ('PAID', 'Pago e liberado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de compra',
                'verbose_name_plural': 'Pedidos de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positivo = crédito; negativo = débito')),
                ('kind', models.CharField(choices=[('FREE_GRANT', 'Créditos gratuitos (boas-vindas)'), ('PURCHASE_SINGLE', 'Compra avulsa — 1 sorteio'), ('PURCHASE_PACK', 'Compra pacote — 30 sorteios'), ('CONSUME', 'Uso em sorteio'), ('ADJUST', 'Ajuste / cortesia'), ('REFUND', 'Estorno')], max_length=20)),
                ('price_cents', models.IntegerField(blank=True, help_text='Valor pago em centavos (apenas em compras)', null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('raffle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='raffles.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.purchaserequest')),
            ],
            options={
                'verbose_name': 'Transação de crédito',
                'verbose_name_plural': 'Transações de crédito',
                'ordering': ['-created_at'],
            },
        ),
    ]
