# Generated by Django 5.2 on 2026-09-14 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('ig_media_id', models.CharField(blank=True, max_length=100)),
                ('permalink', models.URLField(blank=True, max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('media_type', models.CharField(blank=True, max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('comments_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('LOADING', 'Carregando comentários'), ('READY', 'Pronto para sortear'), ('DRAWN', 'Sorteado'), ('FAILED', 'Falha')], default='DRAFT', max_length=10)),
                ('loaded_comments', models.IntegerField(default=0)),
                ('load_started_at', models.DateTimeField(blank=True, null=True)),
                ('load_finished_at', models.DateTimeField(blank=True, null=True)),
                ('load_error', models.TextField(blank=True)),
                ('unique_per_user', models.BooleanField(default=True)),
                ('include_replies', models.BooleanField(default=False)),
                ('exclude_owner', models.BooleanField(default=True)),
                ('min_mentions', models.IntegerField(default=0)),
                ('required_keyword', models.CharField(blank=True, max_length=200)),
                ('excluded_usernames', models.JSONField(blank=True, default=list)),
                ('winners_count', models.IntegerField(default=1)),
                ('alternates_count', models.IntegerField(default=0)),
                ('comments_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('valid_entries', models.IntegerField()),
                ('participants_hash', models.CharField(max_length=64)),
                ('rules_snapshot', models.JSONField(default=dict)),
                ('random_source', models.CharField(default='secrets.SystemRandom', max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Rodada de sorteio',
                'verbose_name_plural': 'Rodadas de sorteio',
                'ordering': ['raffle', 'round'],
                'unique_together': {('raffle', 'round')},
            },
        ),
        migrations.CreateModel(
            name='RaffleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_comment_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('commented_at', models.DateTimeField()),
                ('is_reply', models.BooleanField(default=False)),
                ('parent_ig_id', models.CharField(blank=True, max_length=100)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Comentário do sorteio',
                'verbose_name_plural': 'Comentários do sorteio',
                'indexes': [models.Index(fields=['raffle', 'username'], name='raffles_raf_raffle__068bf4_idx')],
                'unique_together': {('raffle', 'ig_comment_id')},
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('is_alternate', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('ig_comment_id', models.CharField(max_length=100)),
                ('commented_at', models.DateTimeField()),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='raffles.draw')),
            ],
            options={
                'verbose_name': 'Ganhador',
                'verbose_name_plural': 'Ganhadores',
                'ordering': ['draw', 'position'],
                'unique_together': {('draw', 'position')},
            },
        ),
    ]
