upstream sorteio_app {
    server 127.0.0.1:9093 fail_timeout=0;
}

server {
    listen 80;
    server_name sorteio.repsys.com.br;
    client_max_body_size 10m;
    keepalive_timeout 5;

    location /static/ {
        expires max;
        alias /webapps/sorteio/sorteio/staticfiles/;
    }

    location / {
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://sorteio_app;
        proxy_connect_timeout 120;
        proxy_send_timeout 120;
        proxy_read_timeout 120;
    }
}
