; config/server/supervisor.conf
; Copiar para /webapps/sorteio/supervisor.conf
; O Supervisor carrega automaticamente /webapps/*/supervisor.conf
; Após copiar: supervisorctl reread && supervisorctl update

[program:sorteio_web]
command=/webapps/sorteio/venv/bin/gunicorn config.wsgi:application -c /webapps/sorteio/config/server/gunicorn.conf.py
directory=/webapps/sorteio
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/webapps/sorteio/logs/gunicorn.log
stderr_logfile=/webapps/sorteio/logs/gunicorn_error.log

[program:sorteio_worker]
command=/webapps/sorteio/venv/bin/celery -A config worker -Q sorteio -c 2 -l INFO --logfile /webapps/sorteio/logs/celery_worker.log
directory=/webapps/sorteio
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/webapps/sorteio/logs/celery_worker_sup.log
stderr_logfile=/webapps/sorteio/logs/celery_worker_error.log
stopwaitsecs=600
killasgroup=true
priority=998

[program:sorteio_beat]
command=/webapps/sorteio/venv/bin/celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler --logfile /webapps/sorteio/logs/celery_beat.log
directory=/webapps/sorteio
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/webapps/sorteio/logs/celery_beat_sup.log
stderr_logfile=/webapps/sorteio/logs/celery_beat_error.log
stopwaitsecs=600
killasgroup=true
priority=999
